  language: go
  go:
    - "1.8"
    - "1.9"
    - "1.10"
    - "master"
    
  install:
        - go get -d -v ./...
        - go get -d -v golang.org/x/tools/cmd/cover
 
 script:
- go test -v -cover ./...
