# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  repository: iliasku/mikro
  tag: 0.3.0
  pullPolicy: IfNotPresent

service:
  name: mikro
  type: NodePort
  externalPort: 3000
  internalPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi


